docs_dir: ./sources
nav:
- Overview: index.md
- Documentation:
  - Installation: installation.md
  - Conventions: basics.md
  - Physical Model: model.md
  - Analysis: analysis.md
  - Design: design.md
#- Examples: examples.md
# - Python API:
#   - Model: api/model.md
#   - Analysis: api/analysis.md
#   - Design: api/design.md
#   - Concentrations: api/concentration.md
#   - Drawing: api/drawing.md
site_dir: _build/site
site_name: NUPACK User Guide

theme: mkdocs
# theme:
#   name: material
#   language: en
#   palette:
#     primary: orange
#     accent: orange

plugins:
  - search
  # - pdf-export

markdown_extensions:
  - pymdownx.arithmatex
  - footnotes
  - sane_lists
  - smarty
  - admonition
  # - abbr
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      permalink: true
  # - codehilite:
  #     guess_lang: false
  - mdx_bib:
      bibtex_file: nupack.bib
      order: unsorted

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - extra.css

