docs_dir: ./sources
nav:
- Overview: index.md
#- Design: design.md
#- Physical: model.md
#- Conventions: conventions.md
#- Versions: versions.md
#- License: license.md
#- Analysis:
#  - Complex Analysis: complex-analysis.md
#  - Test Tube Analysis: tube-analysis.md
#- Design: 
#  - Complex Design: complex-design.md
#  - Test Tube Design: tube-design.md
#- Getting Started: 
#  - Installation: installation.md
#  - Examples: examples.md
#- Acknowledgments: acknowledgments.md
#- References:
#  - Installation: installation.md
- Conventions: basics.md
- Physical Model: model.md
- Analysis: analysis.md
- Design: design.md
#- Examples: examples.md
# - Python API:
#   - Model: api/model.md
#   - Analysis: api/analysis.md
#   - Design: api/design.md
#   - Concentrations: api/concentration.md
#   - Drawing: api/drawing.md
site_dir: _build/site
site_name: NUPACK User Guide

theme: mkdocs
# theme:
#   name: material
#   language: en
#   palette:
#     primary: orange
#     accent: orange

plugins:
  - search
  # - pdf-export

markdown_extensions:
  - pymdownx.arithmatex
  - footnotes
  - sane_lists
  - smarty
  - admonition
  # - abbr
  - pymdownx.betterem:
      smart_enable: all
  - toc:
      permalink: true
  # - codehilite:
  #     guess_lang: false
  - mdx_bib:
      bibtex_file: nupack.bib
      order: unsorted

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - extra.css

